### ISSUE TITLE
Runtime exception if outdated Google Play Services version

### ISSUE THREAD

**Issue by kevinzetterstrom** [googlecast/CastVideos-android#12]
## Description

The app crashes if using an outdated Google Play Services version
## Crash

```
Caused by: java.lang.RuntimeException: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                                      at com.google.android.gms.internal.zzni.zzbg(Unknown Source)
                                                                                      at com.google.android.gms.internal.zzni.zza(Unknown Source)
                                                                                      at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
                                                                                      at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
                                                                                      at com.google.android.gms.cast.framework.media.uicontroller.UIMediaController.<init>(Unknown Source)
                                                                                      at com.google.android.gms.cast.framework.media.widget.MiniControllerFragment.onCreateView(Unknown Source)
```

**Comment by kevinzetterstrom** [comment]
## Update
It appears that even though the play services version says "9.4.52" it was being picked up as out of date. To fix, Cast Videos needs to check the Google Play services _before_ the first call to ```CastContext.getSharedInstance()```, which happens in MinControllerFragment. Since this Fragment is part of the VideoBrowserActivity, the check needs to happen before the the layout is set.

**Comment by entertailion** [comment]
You should be able to check for this in your activity's onCreate method. If the Google Play services version is not what you expect, load an empty fragment instead of the MiniControllerFragment.

**Comment by kevinzetterstrom** [comment]
This is about this demo failing, not my own application. I think this issue should stay open until the Cast Videos app is fixed.
