### ISSUE TITLE
MediaRouteChooserDialog crashed on rotation if custom theme is applied

### ISSUE THREAD

**Issue by anna-b** [googlecast/CastVideos-android#13]
Ali Naddaf suggested a solution for styling the MediaRouteChooserDialog and MediaRouteControllerDialog by extending the MediaRouteDialogFactory and overriding the implementation of those dialog. Source: http://stackoverflow.com/questions/24245926/mediarouteactionprovider-connection-dialog-theme 
This works well with api v2, but doing the same thing on with api v3 results in the crash, if you have a dialog up and rotation the screen. 

In VideoBrowserActivity, modify onCreateOptionsMenu to the following:
`@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        super.onCreateOptionsMenu(menu);
        getMenuInflater().inflate(R.menu.browse, menu);
        mediaRouteMenuItem = CastButtonFactory.setUpMediaRouteButton(getApplicationContext(), menu,
                R.id.media_route_menu_item);
        mQueueMenuItem = menu.findItem(R.id.action_show_queue);
        mediaRouteMenuItem = CastButtonFactory.setUpMediaRouteButton(getApplicationContext(), menu,
                R.id.media_route_menu_item);
        MediaRouteActionProvider mediaRouteButton = (MediaRouteActionProvider) MenuItemCompat.getActionProvider(mediaRouteMenuItem);
        mediaRouteButton.setDialogFactory(new MediaRouteDialogFactory(){
            @NonNull
            @Override
            public MediaRouteChooserDialogFragment onCreateChooserDialogFragment() {
                return new MediaRouteChooserDialogFragment() {
                    @Override
                    public MediaRouteChooserDialog onCreateChooserDialog(Context context, Bundle savedInstanceState) {
                        return new MediaRouteChooserDialog(getActivity(), R.style.Theme_MediaRouter);
                    }
                };
            }
        });
        showIntroductoryOverlay();
        return true;
    }`

Add the themes.xml with the following: 
`<style name="Theme.MediaRouter" parent="Theme.AppCompat.Light.Dialog.Alert">
        <item name="android:windowNoTitle">false</item>
        <item name="android:textColor">@color/white</item>
        <item name="mediaRouteButtonStyle">@style/Widget.MediaRouter.MediaRouteButton</item>
        <item name="mediaRouteOffDrawable">@drawable/ic_media_route_off_mono_dark</item>
        <item name="mediaRouteCloseDrawable">@drawable/mr_ic_close_light</item>
        <item name="mediaRoutePlayDrawable">@drawable/mr_ic_play_light</item>
        <item name="mediaRoutePauseDrawable">@drawable/mr_ic_pause_light</item>
        <item name="mediaRouteCastDrawable">@drawable/mr_ic_cast_light</item>
        <item name="mediaRouteAudioTrackDrawable">@drawable/ic_audiotrack</item>
        <item name="mediaRouteDefaultIconDrawable">@drawable/ic_tv_dark</item>
        <item name="mediaRouteSpeakerIconDrawable">@drawable/ic_speaker_dark</item>
        <item name="mediaRouteSpeakerGroupIconDrawable">@drawable/ic_speaker_group_dark</item>
        <item name="mediaRouteChooserPrimaryTextStyle">
            @style/Widget.MediaRouter.ChooserText.Primary.Dark
        </item>
        <item name="mediaRouteChooserSecondaryTextStyle">
            @style/Widget.MediaRouter.ChooserText.Secondary.Dark
        </item>
        <item name="mediaRouteControllerTitleTextStyle">
            @style/Widget.MediaRouter.ControllerText.Title.Dark
        </item>
        <item name="mediaRouteControllerPrimaryTextStyle">
            @style/Widget.MediaRouter.ControllerText.Primary.Dark
        </item>
        <item name="mediaRouteControllerSecondaryTextStyle">
            @style/Widget.MediaRouter.ControllerText.Secondary.Dark
        </item>
    </style>`

Run the app, press on the chromecast button, dialog appears, turn the device, application crashes with the following logs: 
`FATAL EXCEPTION: main
                                                                                  Process: com.google.sample.cast.refplayer, PID: 31871
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.sample.cast.refplayer/com.google.sample.cast.refplayer.VideoBrowserActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.google.sample.cast.refplayer.VideoBrowserActivity$2$1: make sure class name exists, is public, and has an empty constructor that is public
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
                                                                                      at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                   Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.google.sample.cast.refplayer.VideoBrowserActivity$2$1: make sure class name exists, is public, and has an empty constructor that is public
                                                                                      at android.support.v4.app.Fragment.instantiate(Fragment.java:431)
                                                                                      at android.support.v4.app.FragmentState.instantiate(Fragment.java:102)
                                                                                      at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1952)
                                                                                      at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:144)
                                                                                      at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:306)
                                                                                      at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
                                                                                      at com.google.sample.cast.refplayer.VideoBrowserActivity.onCreate(VideoBrowserActivity.java:117)
                                                                                      at android.app.Activity.performCreate(Activity.java:6251)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077) 
                                                                                      at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                   Caused by: java.lang.InstantiationException: java.lang.Class<com.google.sample.cast.refplayer.VideoBrowserActivity$2$1> has no zero argument constructor
                                                                                      at java.lang.Class.newInstance(Native Method)
                                                                                      at android.support.v4.app.Fragment.instantiate(Fragment.java:420)
                                                                                      at android.support.v4.app.FragmentState.instantiate(Fragment.java:102) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1952) 
                                                                                      at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:144) 
                                                                                      at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:306) 
                                                                                      at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85) 
                                                                                      at com.google.sample.cast.refplayer.VideoBrowserActivity.onCreate(VideoBrowserActivity.java:117) 
                                                                                      at android.app.Activity.performCreate(Activity.java:6251) 
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077) 
                                                                                      at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
`

**Comment by entertailion** [comment]
Customizing the MediaRouter dialogs is currently not supported in the Cast SDK v3.
