### ISSUE TITLE
llegalArgumentException when showing the IntroductoryOverlay

### ISSUE THREAD

**Issue by anna-b** [googlecast/CastVideos-android#23]
The application crashes with the following error stacktrace:

java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
    at com.google.android.gms.cast.framework.internal.featurehighlight.zza.onDraw(Unknown Source)
    at android.view.View.draw(View.java:17067)
    at android.view.View.updateDisplayListIfDirty(View.java:16049)
    at android.view.View.draw(View.java:16833)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.updateDisplayListIfDirty(View.java:16044)
    at android.view.View.draw(View.java:16833)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17070)
    at com.android.internal.policy.DecorView.draw(DecorView.java:751)
    at android.view.View.updateDisplayListIfDirty(View.java:16049)...

As the googlecast code is obfuscated it is hard to say what exactly goes wrong, but it seems to point to the IntroductoryOverlay from this line in the stacktrace - "at com.google.android.gms.cast.framework.internal.featurehighlight.zza.onDraw(Unknown Source)"

Issue maybe reproduced on LGE Nexus 5X.

**Comment by entertailion** [comment]
File a bug against the Cast SDK and provide a complete log: https://code.google.com/p/google-cast-sdk/issues/list

**Comment by barnhill** [comment]
@anna-b did you ever get a response from google from the ticket you filed?  https://issuetracker.google.com/issues/36191274

**Comment by ashishbhandari** [comment]
I am also facing this issue this is something which is getting crashed internally and the same error any resolution for the same. this issue is quite intermittent and happens on specific devices.
