### ISSUE TITLE
App crashes if stop casting while session is trying to reconnect

### ISSUE THREAD

**Issue by ghost** [googlecast/CastVideos-android#24]
If I start a cast session, and then disconnect wifi then immediately click on cast button and stop casting, the app will crash with below trace:

10-23 17:18:45.894 27189-27189/com.google.sample.cast.refplayer E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.google.sample.cast.refplayer, PID: 27189
Theme: themes:{}
java.lang.IllegalStateException: GoogleApiClient is not connected yet.
    at com.google.android.gms.internal.zzrb.zzb(Unknown Source)
    at com.google.android.gms.internal.zzrf.zzb(Unknown Source)
    at com.google.android.gms.internal.zzrd.zzb(Unknown Source)
    at com.google.android.gms.cast.Cast$CastApi$zza.stopApplication(Unknown Source)
    at com.google.android.gms.cast.framework.CastSession$zzb.zzgo(Unknown Source)
    at com.google.android.gms.cast.framework.zzf$zza.onTransact(Unknown Source)
    at android.os.Binder.transact(Binder.java:387)
    at yn.a(:com.google.android.gms.DynamiteModulesC:184)
    at yd.a(:com.google.android.gms.DynamiteModulesC:120)
    at ys.onTransact(:com.google.android.gms.DynamiteModulesC:122)
    at android.os.Binder.transact(Binder.java:387)
    at com.google.android.gms.cast.framework.zzh$zza$zza.zzb(Unknown Source)
    at com.google.android.gms.cast.framework.CastSession.end(Unknown Source)
    at com.google.android.gms.cast.framework.Session$zza.end(Unknown Source)
    at com.google.android.gms.cast.framework.zzq$zza.onTransact(Unknown Source)
    at android.os.Binder.transact(Binder.java:387)
    at zu.a(:com.google.android.gms.DynamiteModulesC:216)
    at aac.a(:com.google.android.gms.DynamiteModulesC:305)
    at aay.a(:com.google.android.gms.DynamiteModulesC:61)
    at aav.onTransact(:com.google.android.gms.DynamiteModulesC:144)
    at android.os.Binder.transact(Binder.java:387)
    at com.google.android.gms.internal.zzol$zza$zza.zza(Unknown Source)
    at com.google.android.gms.internal.zzoo.onRouteUnselected(Unknown Source)
    at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.invokeCallback(MediaRouter.java:2846)
    at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.handleMessage(MediaRouter.java:2793)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by LeonNicholls** [comment]
Please file a bug against the Cast SDK: https://code.google.com/p/google-cast-sdk/issues/list
