### ISSUE TITLE
Notification was not showing BUG

### ISSUE THREAD

**Issue by iceteahh** [googlecast/CastVideos-android#30]
My scenario when using this sample:
- First i cast a video on list video provided by this sample
- I pressed home button to show up home screen and notification appeared
- I canceled casting by pressed close button on the notification.
- Then i pressed recent button and brought activity back. Cast another video
- Press home button again and "notification didn't appear" 
- Press recent button brought activity back again and error occurred

ERROR
 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.cast.MediaInfo.getContentId()' on a null object reference
            at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerFragment.onResume(VideoCastControllerFragment.java:477)
            at android.support.v4.app.Fragment.performResume(Fragment.java:1832)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1939)
            at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:447)
            at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:436)
            at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:138)
            at android.app.Activity.performResume(Activity.java:6513)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3522)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3564)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6141)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

Fix it please.

**Comment by naddaf** [comment]
Let me make sure I understand the reproduction steps. When you click on the "close" button in notification, it disconnects you from the cast device. In your steps,  don't see where you connect to the cast device again, could you please clarify?

**Comment by naddaf** [comment]
In addition, please update your CCL since line 477 in VideoCastControllerFragment that is in the stack trace doesn't match the current code.

**Comment by iceteahh** [comment]
When i cast another video i connect the chromecast again. Of course connection was successful.

**Comment by naddaf** [comment]
After updating your CCL, please create a new stack trace if the issue still happens.

**Comment by iceteahh** [comment]
OK, I will update my CCL.

**Comment by iceteahh** [comment]
Hi naddaf, i have updated my CCL, and error was not occurred anymore, but the notification sometime didn't show up.

**Comment by iceteahh** [comment]
I create new application using CCL. When chromecast is playing a video, i connect my app to chromecast and get this error:

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.gms.cast.MediaStatus.getLoadingItemId()' on a null object reference
            at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerFragment.updatePlayerStatus(VideoCastControllerFragment.java:474)
            at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerFragment.access$1000(VideoCastControllerFragment.java:75)
            at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerFragment$MyCastConsumer.onRemoteMediaPlayerStatusUpdated(VideoCastControllerFragment.java:259)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2115)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:138)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1793)
            at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
            at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
            at com.google.android.gms.cast.internal.zzm.zzbB(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
            at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6141)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

Can you help me fix this?

**Comment by naddaf** [comment]
Since this is not related to CastVideos-android and it is now your own app, you need to post your question along with adequate information to StackOverflow.
