### ISSUE TITLE
Crash when stop casting

### ISSUE THREAD

**Issue by gemiren** [googlecast/CastVideos-android#31]
Steps to reproduce this crash:
1. Run this example app to cast any sample video
2. Click the cast icon on the toolbar to open the Casting playback control dialog
3. Click "stop casting". The sample app will crash.

Tested in both Android M and Android N phones. Same crash always happens.

Below is the crash stacktrace:
com.google.sample.cast.refplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.google.sample.cast.refplayer, PID: 3615
                                                                                java.lang.NullPointerException: Attempt to write to field 'java.lang.ref.WeakReference android.support.v4.media.session.MediaSessionCompat$Callback.mSessionImpl' on a null object reference
                                                                                    at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setCallback(MediaSessionCompat.java:2305)
                                                                                    at android.support.v4.media.session.MediaSessionCompat.setCallback(MediaSessionCompat.java:267)
                                                                                    at android.support.v4.media.session.MediaSessionCompat.setCallback(MediaSessionCompat.java:255)
                                                                                    at com.google.android.gms.internal.zzxe.zzcb(Unknown Source)
                                                                                    at com.google.android.gms.cast.framework.CastSession.zzbV(Unknown Source)
                                                                                    at com.google.android.gms.cast.framework.CastSession.zza(Unknown Source)
                                                                                    at com.google.android.gms.cast.framework.CastSession$zzb.zzbV(Unknown Source)
                                                                                    at com.google.android.gms.cast.framework.zzf$zza.onTransact(Unknown Source)
                                                                                    at android.os.Binder.transact(Binder.java:499)
                                                                                    at zt.a(:com.google.android.gms.DynamiteModulesC:199)
                                                                                    at zj.a(:com.google.android.gms.DynamiteModulesC:128)
                                                                                    at zy.onTransact(:com.google.android.gms.DynamiteModulesC:122)
                                                                                    at android.os.Binder.transact(Binder.java:499)
                                                                                    at com.google.android.gms.cast.framework.zzh$zza$zza.zzb(Unknown Source)
                                                                                    at com.google.android.gms.cast.framework.CastSession.end(Unknown Source)
                                                                                    at com.google.android.gms.cast.framework.Session$zza.end(Unknown Source)
                                                                                    at com.google.android.gms.cast.framework.zzq$zza.onTransact(Unknown Source)
                                                                                    at android.os.Binder.transact(Binder.java:499)
                                                                                    at aba.a(:com.google.android.gms.DynamiteModulesC:216)
                                                                                    at abi.a(:com.google.android.gms.DynamiteModulesC:305)
                                                                                    at ace.a(:com.google.android.gms.DynamiteModulesC:61)
                                                                                    at acb.onTransact(:com.google.android.gms.DynamiteModulesC:144)
                                                                                    at android.os.Binder.transact(Binder.java:499)
                                                                                    at com.google.android.gms.internal.zzwv$zza$zza.zza(Unknown Source)
                                                                                    at com.google.android.gms.internal.zzwy.onRouteUnselected(Unknown Source)
                                                                                    at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.invokeCallback(MediaRouter.java:2999)
                                                                                    at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.handleMessage(MediaRouter.java:2946)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by LeonNicholls** [comment]
Please file a bug with complete log: https://code.google.com/p/google-cast-sdk/issues/list
