### ISSUE TITLE
App is crashing on android 4.4

### ISSUE THREAD

**Issue by vandzi** [googlecast/CastVideos-android#40]
Can't launch app on android 4.4. Tested with 2 devices.
Exception:

```
03-01 10:29:03.992 8101-8101/? E/VdcInflateDelegate: Exception while inflating <vector>
                                                     org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                         at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
                                                         at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
                                                         at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
                                                         at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:829)
                                                         at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:303)
                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:178)
                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
                                                         at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                         at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                         at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                         at java.lang.reflect.Constructor.constructNative(Native Method)
                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                         at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:226)
                                                         at android.support.v7.app.AppCompatViewInflater.createViewFromTag(AppCompatViewInflater.java:175)
                                                         at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:146)
                                                         at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:963)
                                                         at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1022)
                                                         at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                         at com.google.sample.cast.refplayer.VideoBrowserActivity.onCreate(VideoBrowserActivity.java:58)
                                                         at android.app.Activity.performCreate(Activity.java:5275)
                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
                                                         at android.app.ActivityThread.access$800(ActivityThread.java:142)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:136)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5118)
                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
                                                         at dalvik.system.NativeStart.main(Native Method)
```

**Comment by naddaf** [comment]
This is happening due to a change in v23.2.0 of support libs. I made a change in build.gradle to address that, please resync. Here is an article that explains it: https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.xt2cuokdh

**Comment by vandzi** [comment]
Even after update, still crashing on 4.4. Now with:

```
com.google.sample.cast.refplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.google.sample.cast.refplayer, PID: 12584
                                                                                  android.view.InflateException: Binary XML file line #42: Error inflating class Button
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
                                                                                      at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:109)
                                                                                      at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:100)
                                                                                      at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:79)
                                                                                      at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay$Builder.build(IntroductoryOverlay.java:296)
                                                                                      at com.google.sample.cast.refplayer.VideoBrowserActivity$2.run(VideoBrowserActivity.java:166)
                                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:146)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5727)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                                   Caused by: java.lang.NullPointerException
                                                                                      at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
                                                                                      at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:107)
                                                                                      at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:608)
                                                                                      at android.support.v7.widget.AppCompatDrawableManager.tintDrawable(AppCompatDrawableManager.java:773)
                                                                                      at android.support.v7.widget.AppCompatBackgroundHelper.applySupportBackgroundTint(AppCompatBackgroundHelper.java:118)
                                                                                      at android.support.v7.widget.AppCompatBackgroundHelper.setInternalBackgroundTint(AppCompatBackgroundHelper.java:136)
                                                                                      at android.support.v7.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:53)
                                                                                      at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:66)
                                                                                      at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:58)
                                                                                      at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:963)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1022)
                                                                                      at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                                      at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:109) 
                                                                                      at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:100) 
                                                                                      at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.<init>(IntroductoryOverlay.java:79) 
                                                                                      at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay$Builder.build(IntroductoryOverlay.java:296) 
                                                                                      at com.google.sample.cast.refplayer.VideoBrowserActivity$2.run(VideoBrowserActivity.java:166) 
                                                                                      at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                      at android.os.Looper.loop(Looper.java:146) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5727) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                                      at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by naddaf** [comment]
Can you try this: 
comment out the following line in CastCompanionLivrary-android/res/layout/ccl_intro_overlay.xml:

style="@style/Widget.AppCompat.Button.Colored"

which is in the <Button/> element there and report back?

**Comment by naddaf** [comment]
Let's track this issue on CastCompanionLibrary-android, issue 278.
