### ISSUE TITLE
App crashes on devices or emulator that don't support google play services.

### ISSUE THREAD

**Issue by ofuwape** [googlecast/CastVideos-android#49]
06-29 20:37:01.519 20333-20333/com.google.sample.cast.refplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.sample.cast.refplayer/com.google.sample.cast.refplayer.VideoBrowserActivity}: android.view.InflateException: Binary XML file line #40: Error inflating class fragment
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                                   Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class fragment
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                      at com.google.sample.cast.refplayer.VideoBrowserActivity.onCreate(VideoBrowserActivity.java:53)
                                                                                      at android.app.Activity.performCreate(Activity.java:5104)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                                   Caused by: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                                      at com.google.android.gms.internal.zzwv.zzaw(Unknown Source)
                                                                                      at com.google.android.gms.internal.zzwv.zza(Unknown Source)
                                                                                      at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
                                                                                      at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
                                                                                      at com.google.android.gms.cast.framework.media.uicontroller.UIMediaController.<init>(Unknown Source)
                                                                                      at com.google.android.gms.cast.framework.media.widget.MiniControllerFragment.onCreateView(Unknown Source)
                                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1255)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1472)
                                                                                      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1691)
                                                                                      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3413)
                                                                                      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                                                                                      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378)
                                                                                      at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                                                                                      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                      at com.google.sample.cast.refplayer.VideoBrowserActivity.onCreate(VideoBrowserActivity.java:53) 
                                                                                      at android.app.Activity.performCreate(Activity.java:5104) 
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                                   Caused by: com.google.android.gms.dynamite.DynamiteModule$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                                      at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
                                                                                      at com.google.android.gms.internal.zzwv.zzaw(Unknown Source) 
                                                                                      at com.google.android.gms.internal.zzwv.zza(Unknown Source) 
                                                                                      at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source) 
                                                                                      at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
                                                                                      at com.google.android.gms.cast.framework.media.uicontroller.UIMediaController.<init>(Unknown Source) 
                                                                                      at com.google.android.gms.cast.framework.media.widget.MiniControllerFragment.onCreateView(Unknown Source) 
                                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1255) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1472) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1691) 
                                                                                      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3413) 
                                                                                      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120) 
                                                                                      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378) 
                                                                                      at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33) 
                                                                                      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79) 
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680) 
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                      at com.google.sample.cast.refplayer.VideoBrowserActivity.onCreate(VideoBrowserActivity.java:53) 
                                                                                      at android.app.Activity.performCreate(Activity.java:5104) 
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by James665** [comment]
I have the same issue

02-27 14:30:40.940 11669-11669/com.google.sample.cast.refplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.google.sample.cast.refplayer, PID: 11669
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.sample.cast.refplayer/com.google.sample.cast.refplayer.VideoBrowserActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2859)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2934)
                                                                                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1594)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6592)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                   Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment
                                                                                   Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class fragment
                                                                                   Caused by: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                                      at com.google.android.gms.internal.zzwv.zzaw(Unknown Source:24)
                                                                                      at com.google.android.gms.internal.zzwv.zza(Unknown Source:0)
                                                                                      at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:123)
                                                                                      at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:36)
                                                                                      at com.google.android.gms.cast.framework.media.uicontroller.UIMediaController.<init>(Unknown Source:19)
                                                                                      at com.google.android.gms.cast.framework.media.widget.MiniControllerFragment.onCreateView(Unknown Source:6)
                                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1255)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1472)
                                                                                      at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1691)
                                                                                      at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3440)
                                                                                      at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                                                                                      at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378)
                                                                                      at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                                                                                      at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                      at com.google.sample.cast.refplayer.VideoBrowserActivity.onCreate(VideoBrowserActivity.java:111)
                                                                                      at android.app.Activity.performCreate(Activity.java:6975)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2812)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2934)
                                                                                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1594)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                      at android.os.Looper.loop(Looper.java:164)
02-27 14:30:40.941 11669-11669/com.google.sample.cast.refplayer E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6592)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                   Caused by: com.google.android.gms.dynamite.DynamiteModule$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                                      at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source:157)
                                                                                      at com.google.android.gms.internal.zzwv.zzaw(Unknown Source:5)
                                                                                      	... 36 more

**Comment by LeonNicholls** [comment]
You need to check if the Google Play services is installed: https://developers.google.com/android/guides/setup#ensure_devices_have_the_google_play_services_apk
