### ISSUE TITLE
OOM error on particular devices with some video asset

### ISSUE THREAD

**Issue by AshishAccedo** [googlecast/CastVideos-android#54]
Issue occurring on particular devices while casting where it runs for few seconds then suddenly crashes:

E/art: Throwing OutOfMemoryError "Failed to allocate a 67253676 byte allocation with 16764512 free bytes and 43MB until OOM"
 E/art: Throwing OutOfMemoryError "Failed to allocate a 67253676 byte allocation with 16777120 free bytes and 43MB until OOM"
 E/art: Throwing OutOfMemoryError "Failed to allocate a 67231812 byte allocation with 16777120 free bytes and 43MB until OOM"
E/art: Throwing OutOfMemoryError "Failed to allocate a 67231812 byte allocation with 16777120 free bytes and 43MB until OOM"

09-13 18:40:11.685 29723-30102/com.test.androiddev E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
                                                                        Process: com.test.androiddev, PID: 29723
                                                                        java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.OutOfMemoryError: Failed to allocate a 67253676 byte allocation with 16777120 free bytes and 43MB until OOM
                                                                            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                            at android.graphics.Bitmap.nativeCreateFromParcel(Native Method)
                                                                            at android.graphics.Bitmap.access$100(Bitmap.java:32)
                                                                            at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1484)
                                                                            at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1476)
                                                                            at com.google.android.gms.internal.zzef.zza(Unknown Source)
                                                                            at com.google.android.gms.internal.zzavk.zzn(Unknown Source)
                                                                            at com.google.android.gms.internal.zzave.doInBackground(Unknown Source)
                                                                            at com.google.android.gms.internal.zzave.doInBackground(Unknown Source)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                            at java.lang.Thread.run(Thread.java:818)

**Comment by takn** [comment]
We are seeing a similar crash.. any updates?

**Comment by LeonNicholls** [comment]
Is this the sample app unmodified?
