### ISSUE TITLE
stack size error when I load a live content to remotemediaclient for Chromecast in Android

### ISSUE THREAD

**Issue by m-franco** [googlecast/CastVideos-android#56]
I try to load live contents in the chromecast in my app and after play some live contents the app freezes and crashes with the next error.

`java.lang.StackOverflowError: stack size 8MB
                                                  at com.google.android.gms.internal.zzbcz.getMediaInfo(Unknown Source)
                                                  at com.google.android.gms.internal.zzbcz.getStreamDuration(Unknown Source)
                                                  at com.google.android.gms.cast.framework.media.RemoteMediaClient.getStreamDuration(Unknown Source)
                                                  at com.google.android.gms.cast.framework.CastSession.getSessionRemainingTimeMs(Unknown Source)
                                                  at com.google.android.gms.cast.framework.Session$zza.getSessionRemainingTimeMs(Unknown Source)
                                                  at com.google.android.gms.cast.framework.zzac.onTransact(Unknown Source)
                                                  at android.os.Binder.transact(Binder.java:387)
                                                  at nf.a(:com.google.android.gms.DynamiteModulesC@11951446:10)
                                                  at vc.c(:com.google.android.gms.DynamiteModulesC@11951446:41)
                                                  at vm.n(:com.google.android.gms.DynamiteModulesC@11951446:173)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:12)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                  at vh.a(:com.google.android.gms.DynamiteModulesC@11951446:55)
                                                  at vk.onFinish(:com.google.android.gms.DynamiteModulesC@11951446:18)
                                                  at android.os.CountDownTimer.start(CountDownTimer.java:89)
                                                at v`

I can't catch the error, and I don't know where it happens. I've searched for similar errors, and it seems that nobody refers to the same error.

Any help? Thanks!

**Comment by LeonNicholls** [comment]
Please file a bug against the Cast SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
