### ISSUE TITLE
CastContext is not able to initialize. 

### ISSUE THREAD

**Issue by rjkolli7** [googlecast/CastVideos-android#60]
I was referring this Sample app around 2 months back, it was working fine. Don't know what is wrong suddenly since last day it was not working. CastContext was not able to **CastContext.getSharedInstance()** and also not able to inflate **class="com.google.android.gms.cast.framework.media.widget.MiniControllerFragment"** in xml

So I have debugged this sample, getting following error: 

**Here is a full log [Error log](https://hastebin.com/cajimupigu.vbs)**

As I checked app is crashing when setting up the content view in **VideoBrowserActivity.java line number 111**

`at com.google.sample.cast.refplayer.VideoBrowserActivity.onCreate(VideoBrowserActivity.java:111)`

So it was inflate exception thrown by compiler at RunTime. 

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.sample.cast.refplayer/com.google.sample.cast.refplayer.VideoBrowserActivity}: android.view.InflateException: Binary XML file line #41: Binary XML file line #41: Error inflating class fragment`

XML fragment inflate code

```
<fragment
        android:id="@+id/cast_mini_controller"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:visibility="gone"
        app:castShowImageThumbnail="true"
        class="com.google.android.gms.cast.framework.media.widget.MiniControllerFragment" />
```

Dear contributors @entertailion @barnhill @alexbirkett Could you please have a look into issue?

**Comment by barnhill** [comment]
Are you proguarding it

**Comment by rjkolli7** [comment]
No.
Actually one of my application integrated with ChromeCast. So That time I took this library as a reference. 
Since last day my app is suddenly crashing when it's launching. So I checked the log so get an error while inflating MiniControllerFragment fragment app is crashing.
```
<fragment
        android:id="@+id/cast_mini_controller"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:visibility="gone"
        app:castShowImageThumbnail="true"
        class="com.google.android.gms.cast.framework.media.widget.MiniControllerFragment" />
```

So I came back here and downloaded and debugged **CastVideos-android** this also giving same error. So I have reported issue.

Could you please explain me what is the issue as per the [Error Log?](https://hastebin.com/cajimupigu.vbs)

Did I miss anything? Any SDK or etc.. update required to use CastSDK? 

FYI: I have already updated google play services in my phone.

**Comment by mauimauer** [comment]
Hey there,

we're trying to reproduce this issue on our end, but haven't been able to so far. Could you kindly provide additional details (What device/model are you trying to run this on? What Android version are you on? Are you using the sample code as is, or have you bumped any of the dependencies and/or compileSdk version?)

Cheers,
Sebastian

**Comment by rjkolli7** [comment]
I have observed that it seems an error that only happening in the Huawei and Honor phones. 
Android OS 7 and latest

Yes I am using sample code as it is. I did not change any dependencies or sdk versions.

Please not, this crash is producing for me if Chrome cast is ON at the time of application lunch.

**Comment by ghost** [comment]
@rjkolli7 
Track this it might help you. Even i am also facing same issue for Huawei and vivo phones.
https://issuetracker.google.com/issues/65359941

**Comment by ghost** [comment]
Please, anyone can guide?

I updated the libraries of a cast from 11.x.x to 15.0.1.

But now i am facing issue for an Expanded controller activity.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.balaji.alt, PID: 16296
    java.lang.NoSuchFieldError: No static field ad_skip_text of type I in class Lcom/google/android/gms/cast/framework/R$id; or its superclasses (declaration of 'com.google.android.gms.cast.framework.R$id' appears in /data/app/com.x.x-e6op7nI3T9Bkv2dNCHDYGA==/base.apk)
        at com.google.android.gms.cast.framework.media.widget.ExpandedControllerActivity.onCreate(Unknown Source:803)
        at android.app.Activity.performCreate(Activity.java:7174)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by baichunqiu** [comment]
Caused by: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.internal.cast.zze.zzf(Unknown Source:51)
        at com.google.android.gms.internal.cast.zze.zza(Unknown Source:1)
        at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:37)
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:6)
        at com.google.sample.cast.refplayer.browser.VideoBrowserFragment.onStart(VideoBrowserFragment.java:123)
